# Site settings
title: haicheng的博客
email: chchmlml@163.com
baseurl: ""
url: "https://chchmlml.github.io"
description: >
  这是haicheng的博客，里面是技术跟感悟的东西。
twitter_username: chchmlml
weibo_username: chchmlml
github_username:  chchmlml
motto: "博观而约取，厚积而薄发。"

markdown: kramdown

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile','package.json', 'src', 'node_modules', '*.sh', '*.iml']