#
###################################
# Site wide configuration
####################################
#
title: haicheng的博客
tagline: 'haicheng的博客'
description: '这是haicheng的博客，里面是技术跟感悟的东西。'
baseurl: ""
url: "https://chchmlml.github.io"
keywords: ["Programming", "PHP", "Ruby"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: haicheng
  avatar: blog-author.jpg
  job: "PHP Developer"
  bio: "这是haicheng的博客，里面是技术跟感悟的东西。"
  weibo: chchmlml
  twitter: chchmlml #username
  github: chchmlml #username
  email: chchmlml@163.com
  facebook: chchmlml #username

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile','package.json', 'src', 'node_modules', '*.sh', '*.iml']